apiVersion: v1
kind: Pod
metadata:
  name: fortune
spec:
  containers:
    - name: html-fortune
      image: luksa/fortune
      volumeMounts:
        - name: html
          mountPath: /var/htdocs
          readOnly: true
    - name: web-server
      image: nginx:alpine
      volumeMounts:
        - name: html
          mountPath: /user/share/nginx/html
      ports:
          - containerPort: 80
            protocol: TCP
  volumes:
    - name: html
      emptyDir: 
        medium: Memory
